apiVersion: v1
kind: Secret
metadata:
  name: yb-credentials
  namespace: go-yuga-dist
type: Opaque
stringData:
  host: yb-tservers.go-yuga-dist.svc.cluster.local
  port: "5433"
  user: go_yuga_dist_user
  password: "password"
  dbname: go_yuga_dist
  yugabyte_password: "yugabyte"  # Adding the yugabyte superuser password
  DATABASE_URL: "postgresql://go_yuga_dist_user:password@yb-tservers.go-yuga-dist.svc.cluster.local:5433/go_yuga_dist"
